version: '3.1'

services:
  nginx:
    image: nginx:1.24.0 
    depends_on:
      - nextjs
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  nextjs:
    build: .
    ports:
      - 3000:3000